### ISSUE TITLE
FreeSurfaceLoad Validity from/to heights are not exported to SCIA

### ISSUE THREAD

**Issue by errone92** [jarabroz/Koala#15]
**Describe the bug**
Hello. I am exporting XML's with free surfaces loads using the validity From-to and setting the heights for ValidityFrom and ValidityTo  (eg. ValidityFrom =11.845, ValidityTo = 14.065) but this is not reflected when the file is imported to SCIA. The validity is correctly set as From-To but the heights are 0 in SCIA. Looking at the text of the XML file I see that the heights are not present anywhere where the FSloads are defined and briefly looking at the source code in the WriteFSLoad function it also does not appear to set those numbers anywhere (I am not proficient in VB so perhaps I missed it).  The XML is attached below.

[Koala_NoValidity.zip](https://github.com/jarabroz/Koala/files/6002275/Koala_NoValidity.zip)

![image](https://user-images.githubusercontent.com/46051037/108346792-0ecf1f00-71e0-11eb-8a53-dfe70e0d7b5d.png) 

![image](https://user-images.githubusercontent.com/46051037/108349296-1ba14200-71e3-11eb-851e-83a510a079f1.png)

**Desktop (please complete the following information):**
 - Koala V3.10
 - OS: Windows 10
 - Rhino 6 SR34, Grasshopper 1.0.0007
- SCIA Engineer 19.1.4033

**Comment by jarabroz** [comment]
I did fix and it will be available soon.
