### ISSUE TITLE
Load Panel layers are not imported into SCIA

### ISSUE THREAD

**Issue by errone92** [jarabroz/Koala#17]
**Describe the bug**
The layer name input into the Load Panels component is not reflected in SCIA. On import, all load panels are placed on Layer1. In the XML file the layer definition is there but the layer name is not under the load panel definition. Looking at the source code I believe the wrong value is being taken as the layer in the WriteLoadPanels function. XML is attached.

[Koala_LoadPanelLayerIssue.zip](https://github.com/jarabroz/Koala/files/6003227/Koala_LoadPanelLayerIssue.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/46051037/108365828-f2d77780-71f7-11eb-8f58-b568dc04bc76.png)

**Desktop (please complete the following information):**
 - Koala V3.10
 - OS: Windows 10
 - Rhino 6 SR34, Grasshopper 1.0.0007
 - SCIA Engineer 19.1.4033

**Comment by jarabroz** [comment]
Yeah. You are right. I did copy of function from 2Dmember and forgot to change it. It will be included in the bugfix of v3.10
