### ISSUE TITLE
Free Surface Load value and validity error

### ISSUE THREAD

**Issue by errone92** [jarabroz/Koala#19]
**Describe the bug**
I noticed another issue with free surface loads in Koala V3.10. I have a free surface load vertically on a wall that has validity Z=0. When it is imported into SCIA the load goes to 0 and the Validity changes to All. If the Free Surface Load is horizontal in the XY plane it works fine. This issue happens in V3.10 and V3.9 but in Koala V3.8 it worked fine. You can see below screenshots with V3.8 how it's supposed to be in SCIA and V3.10 how it is going wrong.

![GH_V308](https://user-images.githubusercontent.com/46051037/108506870-c6842f80-72b9-11eb-8283-3d1e5f183ff9.jpg)
![SCIA_V308](https://user-images.githubusercontent.com/46051037/108506884-d13ec480-72b9-11eb-93e5-982b458e7a71.jpg)
 - Koala V3.8

![GH_V310](https://user-images.githubusercontent.com/46051037/108506905-d7cd3c00-72b9-11eb-92c1-47503215033e.jpg)
![SCIA_V310](https://user-images.githubusercontent.com/46051037/108506914-da2f9600-72b9-11eb-81de-f8f1297f0bf2.jpg)
 - Koala V3.10

I looked through the XML files but I can't see any difference except the new lines for Validity to and Validity From. In the zip below are the GH and XML files that show this problem. The two GH files are the same except for the version of Koala used. Thanks.

[FSLoad Issue.zip](https://github.com/jarabroz/Koala/files/6010239/FSLoad.Issue.zip)

**Desktop (please complete the following information):**
 - Koala V3.10
 - OS: Windows 10
 - Rhino 6 SR34, Grasshopper 1.0.0007
 - SCIA Engineer 19.1.4033

**Comment by jarabroz** [comment]
That's bug. I have just did fix and it will be in the next version.
