### ISSUE TITLE
Generate Line Grid in Koala

### ISSUE THREAD

**Issue by errone92** [jarabroz/Koala#21]
**Is your feature request related to a problem? Please describe.**
It would be great to have a component in Koala to generate a line grid. Now we have to create the grid manually after import into SCIA.

**Describe the solution you'd like**
If there was a Koala component that you could, for example, just input a grid of points like what the Rectangular component outputs to automatically generate a line grid would be ideal. Or even inputs for a list of spacings in X, Y, and Z.

**Comment by jarabroz** [comment]
Koala is using SCIA Engineer XML. There is not any support for line grid.  Therefore it is not possible develop in Koala.
