### ISSUE TITLE
Spaces in filepath

### ISSUE THREAD

**Issue by mwdhont** [jarabroz/Koala#9]
Hi Jaroslav,

While I was experimenting with the 'Analysis'-module, I faced the issue that under certain conditions, the process ends with the exit code 4 - 'Unable to open Projectfile'. My feeling is that this is due to the fact that there are spaces in the paths I'm using, see printscreens below. I know from previous experience with the VBA-Excel (https://resources.scia.net/en/garage/parametricbatchoptimizer.htm) that it is possible to circumvent this by adding quotation marks around the path. Nevertheless, this throws me another error, saying that there are invalid characters in the path (see last printscreen).

Could you please confirm my feeling that the occurrence of spaces is the issue here, and propose a solution? I believe it's a mandatory input robustness to have in any case.

Many thanks for your support!
Michiel

**Screenshots**
**Without spaces**
![image](https://user-images.githubusercontent.com/53975317/98354875-a2118980-2021-11eb-9b3a-b9de37ef370a.png)

**With spaces**
![image](https://user-images.githubusercontent.com/53975317/98355784-ef422b00-2022-11eb-9076-d9d97f7ea305.png)

**With quotation marks**
![image](https://user-images.githubusercontent.com/53975317/98355797-f2d5b200-2022-11eb-85dd-18d1c6a93431.png)

**Desktop:**
 - OS: Windows 10
 - Version of Rhino/Grasshopper: Rhino 6 SR30 (6.30.20288.16411) & Grasshopper 1.0.0007
- Version of SCIA Engineer: 19.1

**Comment by jarabroz** [comment]
This is caused by underlaying technology. We are using MyProcess to run Esa_XML.exe within Analysis component.  You cannot use path with spaces for Template name and File Name.
